### ISSUE TITLE
No carga mi postman

### ISSUE THREAD

**Issue by FabianCaamal** [CarlosUh/UTP2019Programacion#4]
quiero cargar el api_token y me carga mi login
![Captura de pantalla (24)](https://user-images.githubusercontent.com/50337714/64369581-4cd38580-cfe2-11e9-86a4-7967caa7a08e.png)

**Comment by Cristobal117** [comment]
No le has agregado el token y así no esta validando el usuario por eso te redirige al login

**Comment by MarioMena117** [comment]
Ya probaste reiniciando el modem? :v

**Comment by FabianCaamal** [comment]
validando el usuario
